---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: pacman-posthook01
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  extra_vars:
    env: production
