---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pacman-ns.yaml
- pacman-ui-deployment.yaml
- pacman-ui-route.yaml
- pacman-ui-svc.yaml
- presync-01-aj.yaml
- presync-02-aj.yaml
- postsync-01-aj.yaml
